name: Validate

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  extract-version:
    name: Extract min/max Terraform versions
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Extract Terraform min/max versions
        id: terraform-min-max
        uses: clowdhaus/terraform-min-max@v1.4.0
        with:
          directory: .
    outputs:
      minVersion: ${{ steps.terraform-min-max.outputs.minVersion }}
      maxVersion: ${{ steps.terraform-min-max.outputs.maxVersion }}

  terraform-validate:
    name: Validate Terraform against all supported versions
    runs-on: ubuntu-24.04
    needs: extract-version
    strategy:
      matrix:
        tf_ver:
          - "${{ needs.extract-version.outputs.minVersion }}"
          - "${{ needs.extract-version.outputs.maxVersion }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Terraform ${{ matrix.tf_ver }}
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.tf_ver }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate
